#SECRET_KEY=<set this here>
DATABASE_USER=root
DATABASE_PASSWORD=testingpw
DATABASE_HOST=layersdb
RABBITMQ_DEFAULT_USER=guest
RABBITMQ_DEFAULT_PASS=guest
#EMAIL_HOST=<set this here>
#EMAIL_PORT=<set this here if not the default>
#EMAIL_USER=<set this here if needed>
#EMAIL_PASSWORD=<set this here if needed>
#EMAIL_USE_SSL=<set this here if needed>
#EMAIL_USE_TLS=<set this here if needed>
DEBUG=0
